In [73]:
import numpy as np

In [74]:
a=[1,2,3,4,5]
myarr=np.array(a)
myarr
               

array([1, 2, 3, 4, 5])

In [75]:
myarr=np.array([1,2,3,4,5,6])
myarr

array([1, 2, 3, 4, 5, 6])

In [3]:
import numpy as np
a=[]
x=int(input("Enter the size of array: "))
for x in range(x):
    var=int(input("enter the number"))
    a.append(var)
arr=np.array(a)
arr



Enter the size of array: 3
enter the number5
enter the number6
enter the number7


array([5, 6, 7])

In [2]:
a=[]
x=int(input("Enter the size of array: "))
for x in range(x):
    var=int(input("enter the number"))
    a.append(var)
arr=np.array(a)
arr



Enter the size of array: 3
enter the number4
enter the number5
enter the number6


NameError: name 'np' is not defined

In [ ]:
#two dimension array

a=[[1,2,3],[4,5,6],[7,8,9]]
myarr=np.array(a)
print(myarr)
print("shape of array is",myarr.shape)
print("dimension of array is",myarr.ndim)

In [ ]:
import numpy as np

#zero function as in array
a=np.zeros(5)
print(a)
#
ab=np.zeros((3,4))
print(ab)

In [ ]:
#ones function
a=np.ones(4)
print(a)

ab=np.ones((4,5))
print(ab)

In [ ]:
#eye function , makes diagonals in "1
x=np.eye(4) #bydefault it make 2dimen 
print(x)

In [ ]:
#we can also command of different row and columns  in "eye " fubct
y=np.eye(3,5) #but by only singel bracket
print(y)

In [ ]:
#same we can change diagnals numer also 
#by diag function
z=np.diag([2,4,6,8])#we have to give list value for that
print(z)


np.diag(z) #for taking our diag array

In [ ]:
import numpy as np
#import random

#randint function with random module
ran=np.random.randint(2,6,4)
print(ran)

In [ ]:
#rand function
#one dimension 
arr=np.random.rand(5)
print(arr)



In [ ]:
#for 2 dimension
arr2=np.random.rand(2,5)
print(arr2)

In [ ]:
#randn funct give values that is very close to  0 number

#for 2 dimension
arr=np.random.randn(5)
print(arr)

In [ ]:
### 